// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PJATK_APBD_Cw7_s27023.Infrastructure;

#nullable disable

namespace PJATK_APBD_Cw7_s27023.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260517162210_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PJATK_APBD_Cw7_s27023.Models.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("char");

                    b.Property<int>("ComponentManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturersId");

                    b.HasIndex("ComponentTypesId");

                    b.ToTable("Components", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "CPU-I9-13K",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 1,
                            Description = "24-core, 32-thread desktop CPU, 5.8 GHz boost",
                            Name = "Intel Core i9-13900K"
                        },
                        new
                        {
                            Code = "CPU-R9-79X",
                            ComponentManufacturersId = 2,
                            ComponentTypesId = 1,
                            Description = "16-core, 32-thread desktop CPU, 5.7 GHz boost",
                            Name = "AMD Ryzen 9 7950X"
                        },
                        new
                        {
                            Code = "GPU-RTX409",
                            ComponentManufacturersId = 3,
                            ComponentTypesId = 2,
                            Description = "Flagship GPU with 24 GB GDDR6X memory",
                            Name = "NVIDIA GeForce RTX 4090"
                        },
                        new
                        {
                            Code = "GPU-RX79XT",
                            ComponentManufacturersId = 2,
                            ComponentTypesId = 2,
                            Description = "High-end GPU with 24 GB GDDR6 memory",
                            Name = "AMD Radeon RX 7900 XTX"
                        },
                        new
                        {
                            Code = "RAM-CV032G",
                            ComponentManufacturersId = 4,
                            ComponentTypesId = 3,
                            Description = "2x16GB DDR5 RGB memory kit",
                            Name = "Corsair Vengeance DDR5-6000 32GB"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s27023.Models.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.Property<DateOnly>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "INTC",
                            FoundationDate = new DateOnly(1968, 7, 18),
                            FullName = "Intel Corporation"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AMD",
                            FoundationDate = new DateOnly(1969, 5, 1),
                            FullName = "Advanced Micro Devices, Inc."
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "NVDA",
                            FoundationDate = new DateOnly(1993, 4, 5),
                            FullName = "NVIDIA Corporation"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "CORS",
                            FoundationDate = new DateOnly(1994, 1, 1),
                            FullName = "Corsair Memory, Inc."
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s27023.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Central Processing Unit"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Processing Unit"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Random Access Memory"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s27023.Models.PC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float(5)");

                    b.HasKey("Id");

                    b.ToTable("PCs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Beast X",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 12.5
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 15, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Mini Pro",
                            Stock = 12,
                            Warranty = 24,
                            Weight = 4.2000000000000002
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 20, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Name = "Workstation Elite",
                            Stock = 3,
                            Warranty = 60,
                            Weight = 18.0
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s27023.Models.PCComponent", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasMaxLength(10)
                        .HasColumnType("char");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents", (string)null);

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "CPU-I9-13K",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "GPU-RTX409",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "RAM-CV032G",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "CPU-R9-79X",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "RAM-CV032G",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "CPU-I9-13K",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "GPU-RX79XT",
                            Amount = 1
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s27023.Models.Component", b =>
                {
                    b.HasOne("PJATK_APBD_Cw7_s27023.Models.ComponentManufacturer", "ComponentManufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJATK_APBD_Cw7_s27023.Models.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s27023.Models.PCComponent", b =>
                {
                    b.HasOne("PJATK_APBD_Cw7_s27023.Models.Component", "Component")
                        .WithMany("PCComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJATK_APBD_Cw7_s27023.Models.PC", "Pc")
                        .WithMany("PCComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Pc");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s27023.Models.Component", b =>
                {
                    b.Navigation("PCComponents");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s27023.Models.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s27023.Models.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s27023.Models.PC", b =>
                {
                    b.Navigation("PCComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
